apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: supabase-external-secret
  namespace: supabase
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: supabase-secret-store
    kind: SecretStore
  target:
    name: supabase-esm-secrets
    creationPolicy: Owner
  data:
    - secretKey: db-username
      remoteRef:
        key: supabase/db
        property: username
    - secretKey: db-password
      remoteRef:
        key: supabase/db
        property: password
    - secretKey: db-database
      remoteRef:
        key: supabase/db
        property: database
    - secretKey: jwt-anonKey
      remoteRef:
        key: supabase/jwt
        property: anonKey
    - secretKey: jwt-serviceKey
      remoteRef:
        key: supabase/jwt
        property: serviceKey
    - secretKey: jwt-secret
      remoteRef:
        key: supabase/jwt
        property: secret
    - secretKey: dashboard-username
      remoteRef:
        key: supabase/dashboard
        property: username
    - secretKey: dashboard-password
      remoteRef:
        key: supabase/dashboard
        property: password
    - secretKey: analytics-publicAccessToken
      remoteRef:
        key: supabase/analytics
        property: publicAccessToken
    - secretKey: analytics-privateAccessToken
      remoteRef:
        key: supabase/analytics
        property: privateAccessToken
    - secretKey: realtime-secretKeyBase
      remoteRef:
        key: supabase/realtime
        property: secretKeyBase
    - secretKey: meta-cryptoKey
      remoteRef:
        key: supabase/meta
        property: cryptoKey
    - secretKey: openAiApiKey
      remoteRef:
        key: supabase/dashboard
        property: openAiApiKey
